+Carga el dataset de vuelos "flights14.csv"

In [1]:
import pandas as pd

In [2]:
dfligh = pd.read_csv('./flights14.csv',index_col=0)
dfligh.head()

,year,month,day,dep_delay,arr_delay,carrier,origin,dest,air_time,distance,hour
1,2014,1,1,14,13,AA,JFK,LAX,359,2475,9
2,2014,1,1,-3,13,AA,JFK,LAX,363,2475,11
3,2014,1,1,2,9,AA,JFK,LAX,351,2475,19
4,2014,1,1,-8,-26,AA,LGA,PBI,157,1035,7
5,2014,1,1,2,1,AA,JFK,LAX,350,2475,13

escribe un programa Pandas para dividir los datos basados en origen u destino. Muestra cada grupo y el número de elementos por grupo

In [3]:
# Agrupar por 'origen' y 'destino'
grupos = dfligh.groupby(['origin', 'dest'])

# Mostrar cada grupo y el número de elementos por grupo
for (origin, dest), grupo in grupos:
    print(f"Grupo origen={origin}, destino={dest}")
    print(grupo)
    print(f"Número de elementos en el grupo: {len(grupo)}\n")

Grupo origen=EWR, destino=ALB
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
1111    2014      1    2         -2        -25      EV    EWR  ALB        30
1646    2014      1    3         88         79      EV    EWR  ALB        29
2178    2014      1    4        220        211      EV    EWR  ALB        32
2184    2014      1    4         35         19      EV    EWR  ALB        32
2799    2014      1    5         47         42      EV    EWR  ALB        26
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
124535  2014      6    4         14         -3      EV    EWR  ALB        32
148942  2014      7    2          0         -9      EV    EWR  ALB        31
150380  2014      7    4         82         66      EV    EWR  ALB        29
151106  2014      7    5         -6        -14      EV    EWR  ALB        35
248316  2014     10   26          8         17      EV    EWR  ALB        34

        distance  hour
1111         143     7
1646         143    23
2178         143    15
2184         143     7
2799         143     8
...          ...   ...
124535       143    13
148942       143     9
150380       143    13
151106       143    11
248316       143    16

[169 rows x 11 columns]
Número de elementos en el grupo: 169

Grupo origen=EWR, destino=ANC
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
127051  2014      6    7          1        -16      UA    EWR  ANC       415
132934  2014      6   14          0          8      UA    EWR  ANC       426
139219  2014      6   21          8        -30      UA    EWR  ANC       404
145470  2014      6   28         36          9      UA    EWR  ANC       404
151274  2014      7    5         45         38      UA    EWR  ANC       429
157519  2014      7   12         -1          5      UA    EWR  ANC       432
163580  2014      7   19         -1        -29      UA    EWR  ANC       411
169256  2014      7   26         17         -1      UA    EWR  ANC       418
175934  2014      8    2         -3          5      UA    EWR  ANC       443
182363  2014      8    9          3         -1      UA    EWR  ANC       429
188665  2014      8   16         -3          2      UA    EWR  ANC       443
194812  2014      8   23         62         59      UA    EWR  ANC       436
201109  2014      8   30          0        -14      UA    EWR  ANC       421

        distance  hour
127051      3370    16
132934      3370    16
139219      3370    16
145470      3370    17
151274      3370    17
157519      3370    16
163580      3370    16
169256      3370    16
175934      3370    16
182363      3370    16
188665      3370    16
194812      3370    17
201109      3370    16
Número de elementos en el grupo: 13

Grupo origen=EWR, destino=ATL
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
278     2014      1    1         -7        -14      DL    EWR  ATL       118
283     2014      1    1         -3        -14      DL    EWR  ATL       120
291     2014      1    1         -1         -1      DL    EWR  ATL       118
296     2014      1    1         13         15      DL    EWR  ATL       119
332     2014      1    1        297        290      DL    EWR  ATL       114
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
252598  2014     10   31         -4        -11      DL    EWR  ATL       108
253170  2014     10   31         50         43      UA    EWR  ATL       113
253181  2014     10   31         -5        -38      UA    EWR  ATL       111
253244  2014     10   31         -9        -15      UA    EWR  ATL       119
253279  2014     10   31         11        -10      UA    EWR  ATL       109

        distance  hour
278          746    14
283          746     6
291          746    15
296          746    16
332          746    16
...          ...   ...
252598       746     7
253170       746    15
253181       746     5
253244       746    11
253279       746     8

[4182 rows x 11 columns]
Número de elementos en el grupo: 4182

Grupo origen=EWR, destino=AUS
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
494     2014      1    1         -4        -16      WN    EWR  AUS       247
708     2014      1    1         76         59      UA    EWR  AUS       220
1206    2014      1    2         51         38      WN    EWR  AUS       243
1349    2014      1    2         40         52      UA    EWR  AUS       249
1782    2014      1    3        125        185      UA    EWR  AUS       212
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
252201  2014     10   30         -5        -56      WN    EWR  AUS       196
252299  2014     10   30         -3        -20      UA    EWR  AUS       201
252377  2014     10   30          3        -21      UA    EWR  AUS       202
253067  2014     10   31          0        -30      WN    EWR  AUS       217
253216  2014     10   31         -5         -2      UA    EWR  AUS       211

        distance  hour
494         1504     9
708         1504    16
1206        1504    10
1349        1504    15
1782        1504    17
...          ...   ...
252201      1504    13
252299      1504    15
252377      1504    19
253067      1504    13
253216      1504    15

[568 rows x 11 columns]
Número de elementos en el grupo: 568

Grupo origen=EWR, destino=AVL
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
372     2014      1    1        148        146      EV    EWR  AVL       101
2166    2014      1    4         59         43      EV    EWR  AVL        92
3334    2014      1    6          3         36      EV    EWR  AVL       122
125430  2014      6    5         -5        -20      EV    EWR  AVL        90
126366  2014      6    6         91         96      EV    EWR  AVL        92
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
249173  2014     10   27         -3        -12      EV    EWR  AVL        87
250079  2014     10   28         -9        -17      EV    EWR  AVL        94
250960  2014     10   29         -7          1      EV    EWR  AVL       106
251937  2014     10   30         -7        -19      EV    EWR  AVL        91
252748  2014     10   31        -12        -14      EV    EWR  AVL        96

        distance  hour
372          583    16
2166         583    14
3334         583    13
125430       583    13
126366       583    14
...          ...   ...
249173       583    13
250079       583    13
250960       583    13
251937       583    13
252748       583    13

[145 rows x 11 columns]
Número de elementos en el grupo: 145

Grupo origen=EWR, destino=AVP
       year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
69984  2014      3   31         83         67      EV    EWR  AVP        25

       distance  hour
69984        93    21
Número de elementos en el grupo: 1

Grupo origen=EWR, destino=BDL
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
4081    2014      1    7         19          6      EV    EWR  BDL        26
4794    2014      1    8         28         23      EV    EWR  BDL        24
4797    2014      1    8         62         46      EV    EWR  BDL        27
4877    2014      1    8        160        150      EV    EWR  BDL        47
5627    2014      1    9         29         20      EV    EWR  BDL        24
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
249059  2014     10   27         -5         10      EV    EWR  BDL        26
249963  2014     10   28         -3         -9      EV    EWR  BDL        26
250848  2014     10   29         -5         -2      EV    EWR  BDL        25
251829  2014     10   30         -4         -2      EV    EWR  BDL        28
252716  2014     10   31         -1          0      EV    EWR  BDL        24

        distance  hour
4081         116    19
4794         116    12
4797         116     9
4877         116    21
5627         116    12
...          ...   ...
249059       116    15
249963       116    15
250848       116    15
251829       116    15
252716       116    15

[210 rows x 11 columns]
Número de elementos en el grupo: 210

Grupo origen=EWR, destino=BNA
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
359     2014      1    1         -5          2      EV    EWR  BNA       133
378     2014      1    1         -1         14      EV    EWR  BNA       138
495     2014      1    1         -2         -6      WN    EWR  BNA       130
496     2014      1    1          0          1      WN    EWR  BNA       119
1105    2014      1    2          0         24      EV    EWR  BNA       154
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
252633  2014     10   31         -4        -11      EV    EWR  BNA       121
252635  2014     10   31         -2         -9      EV    EWR  BNA       117
252674  2014     10   31         -4        -14      EV    EWR  BNA       117
253068  2014     10   31         -6        -40      WN    EWR  BNA       110
253069  2014     10   31          3        -15      WN    EWR  BNA       115

        distance  hour
359          748    13
378          748    15
495          748     7
496          748    13
1105         748    10
...          ...   ...
252633       748     9
252635       748    19
252674       748     6
253068       748    18
253069       748     7

[1797 rows x 11 columns]
Número de elementos en el grupo: 1797

Grupo origen=EWR, destino=BOS
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
91      2014      1    1         -5        -11      B6    EWR  BOS        45
230     2014      1    1         -7        -22      B6    EWR  BOS        40
236     2014      1    1         21          2      B6    EWR  BOS        34
585     2014      1    1         -4         -9      UA    EWR  BOS        43
614     2014      1    1         78         71      UA    EWR  BOS        38
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
253251  2014     10   31         -5        -12      UA    EWR  BOS        35
253253  2014     10   31         11         -5      UA    EWR  BOS        32
253258  2014     10   31         -1         -7      UA    EWR  BOS        38
253275  2014     10   31         -1         -9      UA    EWR  BOS        36
253276  2014     10   31         14         22      UA    EWR  BOS        37

        distance  hour
91           200    11
230          200     8
236          200     6
585          200     7
614          200    13
...          ...   ...
253251       200    17
253253       200    21
253258       200     7
253275       200     8
253276       200    15

[4268 rows x 11 columns]
Número de elementos en el grupo: 4268

Grupo origen=EWR, destino=BQN
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
673     2014      1    1         21          2      UA    EWR  BQN       192
1378    2014      1    2         18         86      UA    EWR  BQN       204
1751    2014      1    3        167        185      UA    EWR  BQN       227
2329    2014      1    4        171        150      UA    EWR  BQN       194
2998    2014      1    5         80        115      UA    EWR  BQN       201
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
248860  2014     10   26         98         85      UA    EWR  BQN       198
249671  2014     10   27         16          2      UA    EWR  BQN       192
251514  2014     10   29          4         -3      UA    EWR  BQN       196
252303  2014     10   30         -3         -5      UA    EWR  BQN       197
253266  2014     10   31         72         64      UA    EWR  BQN       208

        distance  hour
673         1585    21
1378        1585    21
1751        1585    23
2329        1585    23
2998        1585    22
...          ...   ...
248860      1585    22
249671      1585    21
251514      1585    20
252303      1585    20
253266      1585    22

[251 rows x 11 columns]
Número de elementos en el grupo: 251

Grupo origen=EWR, destino=BTV
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
2176    2014      1    4         25         18      EV    EWR  BTV        44
2818    2014      1    5         33         75      EV    EWR  BTV        40
4058    2014      1    7          9         -1      EV    EWR  BTV        45
4096    2014      1    7          4         -5      EV    EWR  BTV        44
4816    2014      1    8         16          2      EV    EWR  BTV        47
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
249058  2014     10   27         -5         -4      EV    EWR  BTV        53
249896  2014     10   28         -5          4      EV    EWR  BTV        46
250819  2014     10   29         -5        -16      EV    EWR  BTV        40
251828  2014     10   30         -1         10      EV    EWR  BTV        50
252643  2014     10   31         -3         -4      EV    EWR  BTV        42

        distance  hour
2176         266     8
2818         266    14
4058         266     7
4096         266    11
4816         266     7
...          ...   ...
249058       266     8
249896       266     8
250819       266     8
251828       266     8
252643       266     8

[300 rows x 11 columns]
Número de elementos en el grupo: 300

Grupo origen=EWR, destino=BUF
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
431     2014      1    1         37         37      EV    EWR  BUF        57
1126    2014      1    2          8         15      EV    EWR  BUF        55
1634    2014      1    3         58         63      EV    EWR  BUF        53
2189    2014      1    4         16         10      EV    EWR  BUF        50
2813    2014      1    5         51         45      EV    EWR  BUF        50
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
250063  2014     10   28         -3         -7      EV    EWR  BUF        54
250949  2014     10   29         -4        -18      EV    EWR  BUF        47
251880  2014     10   30          4          1      EV    EWR  BUF        47
251925  2014     10   30        114         89      EV    EWR  BUF        48
252737  2014     10   31         -4        -16      EV    EWR  BUF        49

        distance  hour
431          282    15
1126         282     6
1634         282    18
2189         282     6
2813         282     7
...          ...   ...
250063       282    10
250949       282    10
251880       282    12
251925       282    12
252737       282    10

[334 rows x 11 columns]
Número de elementos en el grupo: 334

Grupo origen=EWR, destino=BWI
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
394     2014      1    1         35         27      EV    EWR  BWI        38
1108    2014      1    2          6         12      EV    EWR  BWI        56
2171    2014      1    4         53         49      EV    EWR  BWI        36
2781    2014      1    5         -5          9      EV    EWR  BWI        42
3339    2014      1    6         66         57      EV    EWR  BWI        41
...      ...    ...  ...        ...        ...     ...    ...  ...       ...
249063  2014     10   27         -9        -10      EV    EWR  BWI        34
249968  2014     10   28         -2         -3      EV    EWR  BWI        36
250854  2014     10   29          0         -9      EV    EWR  BWI        38
251833  2014     10   30         -2        -13      EV    EWR  BWI        34
252648  2014     10   31          0         -5      EV    EWR  BWI        37

        distance  hour
394          169    22
1108         169     8
2171         169     9
2781         169    13
3339         169    14
...          ...   ...
249063       169    16
249968       169    17
250854       169    17
251833       169    16
252648       169    16

[185 rows x 11 columns]
Número de elementos en el grupo: 185

Grupo origen=EWR, destino=BZN
        year  month  day  dep_delay  arr_delay carrier origin dest  air_time  \
2394    2014      1    4         37         16      UA    EWR  BZN       263
2953    2014      1    5        357        351      UA    EWR  BZN       257
7401    2014      1   11         -4        -14      UA    EWR  BZN       269
13017   2014      1   18         18        -17      UA    EWR  BZN       242
17878   2014      1   25         -1        -29      UA    EWR  BZN       262
23278   2014      2    1         21         -1      UA    EWR  BZN       271
27897   2014      2    8          4         -8      UA    EWR  BZN       271
32537   2014      2   15         13        -12      UA    EWR  BZN       268
38194   2014      2   22         28          2      UA    EWR  BZN       258
38974   2014      2   23          6        -17      UA    EWR  BZN       267
44062   2014      3    1         28         24      UA    EWR  BZN       282
44752   2014      3    2         30         26      UA    EWR  BZN       289
49777   2014      3    8         12         -6      UA    EWR  BZN       257
50466   2014      3    9         -5        -30      UA    EWR  BZN       267
55784   2014      3   15         -2        -27      UA    EWR  BZN       261
56489   2014      3   16          1         -8      UA    EWR  BZN       270
61884   2014      3   22         -2         -9      UA    EWR  BZN       281
62645   2014      3   23          1        -21      UA    EWR  BZN       268
67881   2014      3   29         -4        -25      UA    EWR  BZN       269
68751   2014      3   30          9         12      UA    EWR  BZN       279
127062  2014      6    7         -6          3      UA    EWR  BZN       249
127755  2014      6    8         26         43      UA    EWR  BZN       250
132945  2014      6   14         -4         26      UA    EWR  BZN       245
133718  2014      6   15         27         26      UA    EWR  BZN       248
139205  2014      6   21          7         -6      UA    EWR  BZN       248
139941  2014      6   22         -3        -12      UA    EWR  BZN       242
145423  2014      6   28         -4        -23      UA    EWR  BZN       236
146241  2014      6   29         -2         -6      UA    EWR  BZN       243
151206  2014      7    5         -4         -9      UA    EWR  BZN       248
152043  2014      7    6         42         25      UA    EWR  BZN       240
154775  2014      7    9         -8        -21      UA    EWR  BZN       252
157509  2014      7   12          0         12      UA    EWR  BZN       263
158422  2014      7   13         -3          7      UA    EWR  BZN       260
160767  2014      7   16         59         43      UA    EWR  BZN       227
163491  2014      7   19         -4        -23      UA    EWR  BZN       246
164465  2014      7   20         -2          3      UA    EWR  BZN       244
167209  2014      7   23         98        116      UA    EWR  BZN       256
169851  2014      7   26         14         11      UA    EWR  BZN       255
170787  2014      7   27         21         32      UA    EWR  BZN       244
173549  2014      7   30          0         -2      UA    EWR  BZN       244
176016  2014      8    2         16         -3      UA    EWR  BZN       235
176902  2014      8    3         -7         -9      UA    EWR  BZN       237
179576  2014      8    6         -2         -1      UA    EWR  BZN       251
182478  2014      8    9         -2         -8      UA    EWR  BZN       239
183266  2014      8   10         32         20      UA    EWR  BZN       242
185828  2014      8   13         -1         28      UA    EWR  BZN       248
188698  2014      8   16         -3        -24      UA    EWR  BZN       243
189495  2014      8   17         -5         21      UA    EWR  BZN       243
194847  2014      8   23         -7        -15      UA    EWR  BZN       250
195552  2014      8   24         -8        -28      UA    EWR  BZN       240

Escribe un programa Pandas para calcula la media, desviación estándar, min y max del retraso total de cada orgige-destino

In [4]:
# Calcular la columna 'total_delay'
dfligh['total_delay'] = dfligh['dep_delay'] + dfligh['arr_delay']

# Agrupar por 'origin' y 'dest' y calcular las estadísticas
stats = dfligh.groupby(['origin', 'dest'])['total_delay'].agg(['mean', 'std', 'min', 'max'])

# Mostrar las estadísticas
print(stats)

                  mean         std  min   max
origin dest
EWR    ALB   35.230769   92.478247  -36   618
       ANC   15.307692   43.453777  -30   121
       ATL   32.235533  114.946191  -47  2177
       AUS    5.871479   63.006811  -62   539
       AVL   24.903448   82.071727  -33   625
...                ...         ...  ...   ...
LGA    SYR   23.346386   88.091602  -54   844
       TPA   15.267279   80.570698  -57   964
       TVC   71.500000  183.741200  -41   765
       TYS   17.305389   57.004937  -44   291
       XNA    6.911565   53.977890  -64   320

[221 rows x 4 columns]

Escribe un programa Pandas para dividir un conjunto de datos y agruparlos por dos columnas, y luego ordenar los resultados agregados dentro de los grupos.
En el siguiente conjunto de datos de vuelos, agrupar "date" (fecha completa) y "carrier". Luego ordenar la suma de 'total_delay' dentro de los grupos.

In [5]:
dfligh['date'] = pd.to_datetime(dfligh[['year', 'month', 'day']])

# Calcular la columna 'total_delay'
dfligh['total_delay'] = dfligh['dep_delay'] + dfligh['arr_delay']

gdf = dfligh.groupby(['date', 'carrier']).agg({"total_delay": sum})
gdf["total_delay"].groupby(level=0, group_keys=False).nlargest()

date        carrier
2014-01-01  B6         9383
            UA         5897
            EV         4675
            MQ         3122
            WN         2744
                       ...
2014-10-31  UA         4862
            AA         3090
            VX           14
            HA           -4
            F9          -20
Name: total_delay, Length: 1520, dtype: int64

Escribe un programa Pandas para contar el múmero de retrasos de salida por mes y origen.

dfligh.groupby(['month', 'origin'])['dep_delay'].size() agrupa el DataFrame dfligh por las columnas month y origin, y luego cuenta el número de ocurrencias de dep_delay en cada grupo.
.reset_index(name='count') convierte el resultado en un DataFrame y renombra la columna de conteo a count.
print(count_dep_delay.to_string(index=False)) muestra el DataFrame resultante sin los índices.
Este método es útil para obtener el número de ocurrencias de un valor específico en diferentes grupos dentro de un DataFrame.

In [6]:
# Agrupar por 'month' y 'origin' y contar el número de 'dep_delay'
count_dep_delay = dfligh.groupby(['month', 'origin'])['dep_delay'].size().reset_index(name='count')

# Mostrar los resultados
print(count_dep_delay.to_string(index=False))

 month origin  count
     1    EWR   8197
     1    JFK   7105
     1    LGA   7494
     2    EWR   7220
     2    JFK   6779
     2    LGA   6814
     3    EWR   9478
     3    JFK   8253
     3    LGA   8692
     4    EWR   8601
     4    JFK   8070
     4    LGA   8917
     5    EWR   8525
     5    JFK   8305
     5    LGA   8692
     6    EWR   9349
     6    JFK   8422
     6    LGA   8717
     7    EWR   9448
     7    JFK   8730
     7    LGA   8825
     8    EWR   9433
     8    JFK   8986
     8    LGA   9031
     9    EWR   8546
     9    JFK   8228
     9    LGA   8416
    10    EWR   8603
    10    JFK   8605
    10    LGA   8835

5. Escribe un programa pandas para cargar los datos de productos y ventas del archivo foodmarkets.xlsx y mezclarlos en un solo dataframe

In [7]:
import pandas as pd

# Cargar las hojas de cálculo del archivo Excel
productos_df = pd.read_excel('./FoodMarket.xlsx', sheet_name='Products')
ventas_df = pd.read_excel('./FoodMarket.xlsx', sheet_name='Purchases')

# Mezclar los DataFrames en uno solo
merged_df = pd.merge(productos_df, ventas_df, on='Product')

# Mostrar las primeras filas del DataFrame resultante
print(merged_df.head())

   Product Name.x  provider      Price  Code  Seller  Buyer      Fecha  \
0       65  Tapas         4  35.811033    45       1    108 2020-11-03
1       65  Tapas         4  35.811033    72      44      8 2020-09-23
2       65  Tapas         4  35.811033   126      20    120 2020-08-28
3       65  Tapas         4  35.811033   228      42     17 2020-08-07
4       65  Tapas         4  35.811033   410      21    159 2020-05-09

   Quantity
0        26
1        38
2        30
3        29
4        36

In [8]:
merged_df
merged_df.rename(columns={'Name.x': 'ProductName'}, inplace=True)

from tabulate import tabulate

print(tabulate(merged_df.head(), headers='keys'))

      Product  ProductName      provider    Price    Code    Seller    Buyer  Fecha                  Quantity
--  ---------  -------------  ----------  -------  ------  --------  -------  -------------------  ----------
 0         65  Tapas                   4   35.811      45         1      108  2020-11-03 00:00:00          26
 1         65  Tapas                   4   35.811      72        44        8  2020-09-23 00:00:00          38
 2         65  Tapas                   4   35.811     126        20      120  2020-08-28 00:00:00          30
 3         65  Tapas                   4   35.811     228        42       17  2020-08-07 00:00:00          29
 4         65  Tapas                   4   35.811     410        21      159  2020-05-09 00:00:00          36

In [9]:
#!pip install tabulate

6. Escribe un programa Pandas para extraer información sobre el número de compras totales y el monto total por nombre de producto y año.

merged_df['Fecha'] = pd.to_datetime(merged_df['Fecha']) convierte la columna Fecha al tipo de datos datetime.
merged_df.groupby(['ProductName', merged_df['Fecha'].dt.year]) agrupa el DataFrame por ProductName y el año de la columna Fecha.
.agg({'Quantity': 'sum', 'Price': 'sum'}) aplica la función de suma a las columnas Quantity y Price para cada grupo.
.reset_index() restablece el índice del DataFrame resultante para que las columnas de agrupación se conviertan en columnas normales.
Este método es útil para realizar agregaciones en datos agrupados por múltiples columnas, incluyendo la extracción de partes específicas de una columna de fecha.

In [10]:
gdf =merged_df.groupby(['ProductName', merged_df['Fecha'].dt.year]).agg({'Quantity':sum, 'Price':sum})
gdf

                                               Quantity       Price
ProductName                             Fecha
American cheeses                        2019        183   53.481556
                                        2020        384  115.876704
                                        2021         97   26.740778
Appellation d'Origine Contrôlée cheeses 2019        241   85.645240
                                        2020        184   53.528275
...                                                 ...         ...
Vegetables                              2019        249  259.493442
                                        2020        108  148.281967
Vodkas                                  2019        348  525.258332
                                        2020        187  282.831410
                                        2021         66   80.808974

[205 rows x 2 columns]

REESTRUCTURAR DATAFRAMES

In [11]:
datos = {'nombre': ['María', 'Luis', 'Carmen'],
         'edad': [18, 22, 20],
         'Matemáticas': [8.5, 7, 3.5],'Economia': [5, 7, 3],'Programación': [8, 7, 5],}

In [12]:
df= pd.DataFrame(datos)
print(tabulate(df, headers='keys'))

    nombre      edad    Matemáticas    Economia    Programación
--  --------  ------  -------------  ----------  --------------
 0  María         18            8.5           5               8
 1  Luis          22            7             7               7
 2  Carmen        20            3.5           3               5

id_vars=['nombre'] especifica que la columna nombre debe mantenerse como identificador.
value_vars=['Matemáticas', 'Economia', 'Programación'] especifica las columnas que deben ser transformadas de formato ancho a formato largo.
var_name='Asignatura' especifica el nombre de la nueva columna que contendrá los nombres de las asignaturas.
value_name='Nota' especifica el nombre de la nueva columna que contendrá las notas correspondientes.

In [13]:
dfm =df.melt(id_vars=['nombre'], value_vars=['Matemáticas', 'Economia', 'Programación'], var_name='Asignatura', value_name='Nota')
dfm

   nombre    Asignatura  Nota
0   María   Matemáticas   8.5
1    Luis   Matemáticas   7.0
2  Carmen   Matemáticas   3.5
3   María      Economia   5.0
4    Luis      Economia   7.0
5  Carmen      Economia   3.0
6   María  Programación   8.0
7    Luis  Programación   7.0
8  Carmen  Programación   5.0

columns='Asignatura' especifica que los valores únicos de la columna Asignatura deben convertirse en las nuevas columnas.
index='nombre' especifica que los valores únicos de la columna nombre deben convertirse en el índice del DataFrame.
values='Nota' especifica que los valores de la columna Nota deben llenarse en las celdas del DataFrame.
El DataFrame resultante df_pivot está en formato ancho, donde cada columna representa una asignatura y cada fila representa un estudiante con sus respectivas notas.

In [14]:
dfm.pivot(columns='Asignatura', index='nombre', values='Nota')

Asignatura  Economia  Matemáticas  Programación
nombre
Carmen           3.0          3.5           5.0
Luis             7.0          7.0           7.0
María            5.0          8.5           8.0